### ISSUE TITLE
添加hystrix jar包

### ISSUE THREAD

**Issue by longfeizheng** [comedsh/spirngcloud-demo#1]
commons/support 下的pom.xml添加 hystrix依赖

`<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-hystrix</artifactId>
</dependency>`

**Comment by comedsh** [comment]
hystrix 包会被 spring-cloud-starter-feign 依赖载入，所以无需显示加载；只是有时候循环依赖层次过深，或许网络延迟导致包加载失败，这个时候一般多跑几次 mvn compile 或者 mvn -X compile 便可以解决;
<img width="956" alt="github temp" src="https://user-images.githubusercontent.com/8957815/36928503-5d548b6c-1ec1-11e8-8e22-de05226f930b.png">
